version: '3'

services:
  hugo:
    container_name: hugo
    build:
      dockerfile: Dockerfile
      context: .
      args:
        HUGO_VERSION: $HUGO_VERSION
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
